### ISSUE TITLE
lede 仓库代码 make menuconfig 中 Target Devices 里面找不到 redmi ax6

### ISSUE THREAD

**Issue by muboy** [fichenx/Actions-OpenWrt#1]
lede 仓库代码 make menuconfig 中 Target Devices 里面找不到 redmi ax6 这个选项，请问大佬是怎么操作的？
![image](https://user-images.githubusercontent.com/30256195/193259707-bdee6631-ffcc-400e-b4c5-1339e5f3cecb.png)

**Comment by fichenx** [comment]
我是fork这位大佬的代码：https://github.com/breakings/OpenWrt

把这几个文件
https://github.com/fichenx/OpenWrt/tree/main/general/AX6
恢复回去就行了。
详见编译文件
 https://github.com/fichenx/OpenWrt/blob/main/.github/workflows/Build_OP_Redmi-AX6.yml
里这段代码：
- name: Revert some drop sh*t
      run: cp -rf $GITHUB_WORKSPACE/general/AX6/* openwrt/

**Comment by muboy** [comment]
感谢！

**Comment by fichenx** [comment]
close
