### ISSUE TITLE
编译Newifi-D2，Create releases失败

### ISSUE THREAD

**Issue by ghwrf** [fichenx/Actions-OpenWrt#13]
编译Newifi-D2，Create releases失败，提示错误：
[error]Error undefined: Parameter token or opts.auth is required

求指点

**Comment by fichenx** [comment]
需要在你的项目里添加访问令牌变量： RELEASES_TOKEN
![Actions-secrets-·-fichenx-Actions-OpenWrt-10-15-2024_11_36_PM](https://github.com/user-attachments/assets/b6d40585-c8ce-48dc-8560-34481bc01bd1)

创建个人访问令牌地址：
https://github.com/settings/tokens

**Comment by ghwrf** [comment]
感谢大佬。
我创建了令牌，现在又提示错误：Error 500: Cannot convert argument to a ByteString because the character at index 17 has a value of 65509 which is greater than 255.
还是在Create releases部分。
