### ISSUE TITLE
NSS 不起作用。求解

### ISSUE THREAD

**Issue by lingandken** [fichenx/Actions-OpenWrt#3]
我跑网速测试。CPU占用很多。能恢复NSS的工作吗。

**Comment by fichenx** [comment]
ax6吗，可能是因为换源码了。
immortalwrt防火墙是有“路由/NAT 分载”，不知道是不是和NSS效果一样。
另外，恢复了lede版，因无线驱动问题，使用2023年5月4日前源码，只更新插件。
