### ISSUE TITLE
AX6 bypass没有了

### ISSUE THREAD

**Issue by Jonekadsen** [fichenx/Actions-OpenWrt#4]
配置文件的更改，并没有编译出bypass，只剩openclassh。openclassh内核下载及其复杂，几乎等于没法用，希望加回bypas

**Comment by fichenx** [comment]
lede 5月4日以后的源码无线驱动有问题，导致无线一直不能使用。源码更换为immortalwrt了，immortalwrt的luci好像和lede的不太兼容，不支持bypass。immortalwrt支持：luci-app-homeproxy、luci-app-passwall、luci-app-ssr-plus、luci-app-vssr。

**Comment by Jonekadsen** [comment]
emmm，那是否可以加入vssr呢，我自己从软件包里安装的vssr用不了🤔

**Comment by fichenx** [comment]
immortalwrt版已添加vssr。
另外，已恢复lede版的openwrt，只不过使用的是2023年5月4日前的旧源码，只更新插件，此插件包含bypass。
