### ISSUE TITLE
求一个红米ax6原厂分区刷机教程

### ISSUE THREAD

**Issue by clks01** [fichenx/Actions-OpenWrt#6]
现在已经取得ssh密码 可以登录后台
下一步怎么刷机 不知道

『因lede源码无线驱动问题，Redmi AX6（lede固件）暂时维持源码版本在20230501。』

是不是说 默认有无线驱动 可以刷好机就可以用

**Comment by fichenx** [comment]
是的，无线驱动可以正常使用。
刷机教程 恩山论坛有，可以参考这个帖子：
https://www.right.com.cn/forum/thread-5774296-1-2.html
