### ISSUE TITLE
如何更新

### ISSUE THREAD

**Issue by Jonekadsen** [fichenx/Actions-OpenWrt#9]
求问如何更新呢下载的包后台里选择更新都显示包有问题

**Comment by fichenx** [comment]
ARMv8系列可以使用晶晨宝盒更新（手动上传或在线下载更新）
其他固件在系统-备份/升级-刷写新的固件

**Comment by Jonekadsen** [comment]
> ARMv8系列可以使用晶晨宝盒更新（手动上传或在线下载更新） 其他固件在系统-备份/升级-刷写新的固件

ax6的，但是刷写回显示包有问题，刷不进去
